name: PR-Lint
on:
  pull_request:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zeroasiccorp/sbtest:latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint with Verible
        run: |
          find . \( \
            -name "*.v" \
            -or -name "*.sv" \
            -or -name "*.vh" \
            -or -name "*.svh" \
          \) -not \( \
            -path "./switchboard/deps/*" \
            -or -path "./examples/deps/*" \
            -or -name "axil_interconnect_wrap_1x2.v" \
            -or -name "picorv32.v" \
            -or -name "sb_loopback.v" \
          \) > files.txt
          cat files.txt
          verible-verilog-lint \
            --rules_config verible_lint.txt \
            `cat files.txt`
